Create pull_request_template.md
Lambda-School-Labs/citrics-fe-a pull request #3
Opened 2020-10-29 20:19 UTC by adonispuente

2020-10-29 21:11 UTC, mhidalgo83 requested changes
Need to change line 13 from @Lambda-School-Labs/citrics-be-a to @Lambda-School-Labs/citrics-fe-a

2020-11-02 18:56 UTC, kc0buk approved these changes

2020-11-02 18:58 UTC, kc0buk approved these changes
Fixed repo name on line 15

2020-11-02 18:59 UTC, mhidalgo83 approved these changes

2020-11-02 19:00 UTC, merged